const equipos = [
  {
    nombre: "Alajuelense",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
  {
    nombre: "Saprissa",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
  {
    nombre: "Cartaginés",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
  {
    nombre: "Herediano",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
  {
    nombre: "Sporting",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
  {
    nombre: "Guadalupe",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
  {
    nombre: "San Carlos",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
  {
    nombre: "Guanacasteca",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
  {
    nombre: "Municipal Grecia",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
  {
    nombre: "Puntarenas FC",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
  {
    nombre: "Santos de Guápiles",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
  {
    nombre: "Perez Zeledón",
    puntos: 0,
    ganados: 0,
    derrotas: 0,
    empates: 0,
    l: 0,
    v: 0,
    golesfavor: 0,
    golescontra: 0,
    diferenciagoles: 0,
  },
];
